### ISSUE TITLE
Update dependencies to the latest version

### ISSUE THREAD

**Issue by afmika** [second-state/wasmedge-bindgen#12]
Here is my `Cargo.toml`
```toml
[dependencies]
# ...
wasmedge-sdk = {git = "https://github.com/WasmEdge/WasmEdge", tag = "0.12.1"}
wasmedge-sys = {git = "https://github.com/WasmEdge/WasmEdge", tag = "0.12.1"}
wasmedge-sdk-bindgen = "0.4.0"
# ...
```
And here is what I get
```
error: failed to select a version for `wasmedge-sys`.
    ... required by package `wasmedge-sdk v0.4.0`
    ... which satisfies dependency `wasmedge-sdk = "^0.4.0"` of package `wasmedge-sdk-bindgen v0.4.0`
    ... which satisfies dependency `wasmedge-sdk-bindgen = "^0.4.0"` of package `wasmedge v0.1.0 (/home/afmika/dev-env/python-wasi-reactor/python-wasi-reactor/wasmedge)`
versions that meet the requirements `^0.9.0` are: 0.9.0
```
